import type { OpenApiOperationInventoryItem } from "../openapi/openapi-inventory.js";

export type GeneratedContractTestFile = {
  path: string;
  content: string;
};

export function generateContractTestSkeleton(input: {
  sourceKey: string;
  operations: OpenApiOperationInventoryItem[];
  outputPath: string;
}): GeneratedContractTestFile {
  const cases = input.operations
    .filter((operation) => operation.operationId !== undefined)
    .map((operation) => {
      const successStatusCodes = operation.responseStatuses.filter((status) =>
        status.startsWith("2"),
      );
      const errorStatusCodes = operation.responseStatuses.filter(
        (status) => !status.startsWith("2"),
      );

      return `it(${JSON.stringify(`${operation.method.toUpperCase()} ${operation.path} has documented success and error responses`)}, () => {
  expect(${JSON.stringify(successStatusCodes)}.length).toBeGreaterThan(0);
  // Error responses are recommended for UI error handling.
  expect(${JSON.stringify(errorStatusCodes)}.length).toBeGreaterThanOrEqual(0);
});`;
    })
    .join("\n\n");

  return {
    path: input.outputPath,
    content: `// AUTO-GENERATED by spec-to-pr.
// This is a contract skeleton. Extend with generated Zod schemas where available.

import { describe, expect, it } from "vitest";

describe(${JSON.stringify(`${input.sourceKey} OpenAPI contract`)}, () => {
${indent(cases, 2)}
});
`,
  };
}

function indent(value: string, spaces: number): string {
  const prefix = " ".repeat(spaces);

  return value
    .split("\n")
    .map((line) => (line.length === 0 ? line : `${prefix}${line}`))
    .join("\n");
}
