import type { OpenApiOperationInventoryItem } from "../openapi/openapi-inventory.js";

export type GeneratedMockFile = {
  path: string;
  content: string;
};

export function generateMswHandlers(input: {
  sourceKey: string;
  operations: OpenApiOperationInventoryItem[];
  outputPath: string;
}): GeneratedMockFile {
  const handlers = input.operations
    .filter((operation) => operation.operationId !== undefined)
    .map((operation) => renderHandler(operation))
    .join("\n\n");

  return {
    path: input.outputPath,
    content: `// AUTO-GENERATED by spec-to-pr. Review fixture data before use.
import { http, HttpResponse } from "msw";

export const ${camelCase(input.sourceKey)}Handlers = [
${indent(handlers, 2)}
];
`,
  };
}

function renderHandler(operation: OpenApiOperationInventoryItem): string {
  const mswMethod = operation.method.toLowerCase();
  const path = operation.path.replace(/{([^}]+)}/g, ":$1");

  return `http.${mswMethod}(${JSON.stringify(path)}, () => {
  return HttpResponse.json({});
}),`;
}

function camelCase(value: string): string {
  return value
    .replace(/[^A-Za-z0-9]+(.)/g, (_match, chr: string) => chr.toUpperCase())
    .replace(/^[A-Z]/, (chr) => chr.toLowerCase());
}

function indent(value: string, spaces: number): string {
  const prefix = " ".repeat(spaces);

  return value
    .split("\n")
    .map((line) => (line.length === 0 ? line : `${prefix}${line}`))
    .join("\n");
}
