export type ZodGenerationResult = {
  content: string;
  warnings: string[];
};

type SchemaLike = Record<string, unknown>;

export function generateZodSchemas(input: {
  schemas: Record<string, SchemaLike>;
}): ZodGenerationResult {
  const warnings: string[] = [];
  const lines: string[] = [
    "/* eslint-disable */",
    "// AUTO-GENERATED by spec-to-pr. DO NOT EDIT.",
    'import { z } from "zod";',
    "",
  ];

  for (const [name, schema] of Object.entries(input.schemas)) {
    lines.push(`export const ${safeSchemaConstName(name)} = ${schemaToZod(schema, warnings)};`);
    lines.push(`export type ${safeTypeName(name)} = z.infer<typeof ${safeSchemaConstName(name)}>;`);
    lines.push("");
  }

  return {
    content: `${lines.join("\n").trimEnd()}\n`,
    warnings,
  };
}

function schemaToZod(schema: SchemaLike, warnings: string[]): string {
  const ref = schema["$ref"];

  if (typeof ref === "string") {
    return refToZodName(ref);
  }

  const enumValue = schema["enum"];

  if (Array.isArray(enumValue) && enumValue.length > 0) {
    const values = enumValue.filter((item): item is string => typeof item === "string");

    if (values.length === enumValue.length && values.length > 0) {
      return `z.enum([${values.map((value) => JSON.stringify(value)).join(", ")}])`;
    }

    return `z.union([${enumValue.map((value) => `z.literal(${JSON.stringify(value)})`).join(", ")}])`;
  }

  if (Array.isArray(schema["oneOf"]) || Array.isArray(schema["anyOf"])) {
    warnings.push("oneOf/anyOf was converted to z.unknown() by fallback generator.");
    return "z.unknown()";
  }

  if (Array.isArray(schema["allOf"])) {
    warnings.push("allOf was converted to z.unknown() by fallback generator.");
    return "z.unknown()";
  }

  const type = schema["type"];

  let expression: string;

  if (type === "string") {
    expression = stringSchemaToZod(schema);
  } else if (type === "number") {
    expression = "z.number()";
  } else if (type === "integer") {
    expression = "z.number().int()";
  } else if (type === "boolean") {
    expression = "z.boolean()";
  } else if (type === "array") {
    const items = isRecord(schema["items"]) ? schema["items"] : {};
    expression = `z.array(${schemaToZod(items, warnings)})`;
  } else if (type === "object" || isRecord(schema["properties"])) {
    expression = objectSchemaToZod(schema, warnings);
  } else {
    expression = "z.unknown()";
  }

  if (schema["nullable"] === true) {
    return `${expression}.nullable()`;
  }

  return expression;
}

function stringSchemaToZod(schema: SchemaLike): string {
  const format = schema["format"];

  if (format === "uuid") {
    return "z.string().uuid()";
  }

  if (format === "date-time") {
    return "z.string().datetime()";
  }

  if (format === "date") {
    return "z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/)";
  }

  return "z.string()";
}

function objectSchemaToZod(schema: SchemaLike, warnings: string[]): string {
  const properties = isRecord(schema["properties"]) ? schema["properties"] : {};
  const required = new Set(
    Array.isArray(schema["required"])
      ? schema["required"].filter((item): item is string => typeof item === "string")
      : [],
  );

  const members = Object.entries(properties).map(([key, rawProperty]) => {
    const property = isRecord(rawProperty) ? rawProperty : {};
    const optional = required.has(key) ? "" : ".optional()";

    return `  ${JSON.stringify(key)}: ${schemaToZod(property, warnings)}${optional},`;
  });

  return `z.object({\n${members.join("\n")}\n})`;
}

function refToZodName(ref: string): string {
  const marker = "#/components/schemas/";

  if (!ref.startsWith(marker)) {
    return "z.unknown()";
  }

  return safeSchemaConstName(ref.slice(marker.length));
}

function safeTypeName(name: string): string {
  const safe = name.replace(/[^A-Za-z0-9_]/g, "_");

  if (/^[0-9]/.test(safe)) {
    return `Schema_${safe}`;
  }

  return safe;
}

function safeSchemaConstName(name: string): string {
  return `${safeTypeName(name)}Schema`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
