export type SchemaLike = Record<string, unknown>;

export type TypeScriptGenerationResult = {
  content: string;
  warnings: string[];
};

export function generateTypescriptTypes(input: {
  schemas: Record<string, SchemaLike>;
}): TypeScriptGenerationResult {
  const warnings: string[] = [];
  const lines: string[] = [
    "/* eslint-disable */",
    "// AUTO-GENERATED by spec-to-pr. DO NOT EDIT.",
    "",
  ];

  for (const [name, schema] of Object.entries(input.schemas)) {
    lines.push(`export type ${safeTypeName(name)} = ${schemaToTypeScript(schema, warnings)};`);
    lines.push("");
  }

  return {
    content: `${lines.join("\n").trimEnd()}\n`,
    warnings,
  };
}

function schemaToTypeScript(schema: SchemaLike, warnings: string[]): string {
  const ref = schema["$ref"];

  if (typeof ref === "string") {
    return refToTypeName(ref);
  }

  const enumValue = schema["enum"];

  if (Array.isArray(enumValue)) {
    return enumValue.map((value) => JSON.stringify(value)).join(" | ");
  }

  if (Array.isArray(schema["oneOf"]) || Array.isArray(schema["anyOf"])) {
    warnings.push("oneOf/anyOf was converted to unknown for fallback TypeScript generation.");
    return "unknown";
  }

  if (Array.isArray(schema["allOf"])) {
    warnings.push("allOf was converted to intersection only when refs are simple.");
    const parts = schema["allOf"]
      .filter((item): item is SchemaLike => isRecord(item))
      .map((item) => schemaToTypeScript(item, warnings));

    return parts.length === 0 ? "unknown" : parts.join(" & ");
  }

  const type = schema["type"];

  if (type === "string") {
    return "string";
  }

  if (type === "number" || type === "integer") {
    return "number";
  }

  if (type === "boolean") {
    return "boolean";
  }

  if (type === "array") {
    const items = isRecord(schema["items"]) ? schema["items"] : {};
    return `Array<${schemaToTypeScript(items, warnings)}>`;
  }

  if (type === "object" || isRecord(schema["properties"])) {
    return objectSchemaToTypeScript(schema, warnings);
  }

  return "unknown";
}

function objectSchemaToTypeScript(schema: SchemaLike, warnings: string[]): string {
  const properties = isRecord(schema["properties"]) ? schema["properties"] : {};
  const required = new Set(
    Array.isArray(schema["required"])
      ? schema["required"].filter((item): item is string => typeof item === "string")
      : [],
  );

  const members = Object.entries(properties).map(([key, rawProperty]) => {
    const property = isRecord(rawProperty) ? rawProperty : {};
    const optional = required.has(key) ? "" : "?";
    const nullable = property["nullable"] === true ? " | null" : "";

    return `  ${JSON.stringify(key)}${optional}: ${schemaToTypeScript(property, warnings)}${nullable};`;
  });

  if (members.length === 0) {
    return "Record<string, unknown>";
  }

  return `{\n${members.join("\n")}\n}`;
}

function refToTypeName(ref: string): string {
  const marker = "#/components/schemas/";

  if (!ref.startsWith(marker)) {
    return "unknown";
  }

  return safeTypeName(ref.slice(marker.length));
}

function safeTypeName(name: string): string {
  const safe = name.replace(/[^A-Za-z0-9_]/g, "_");

  if (/^[0-9]/.test(safe)) {
    return `Schema_${safe}`;
  }

  return safe;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
