export type SourceGuardGenerationInput = {
  generatedImportPattern: string;
  uiGlobs: string[];
  outputPath: string;
};

export type GeneratedSourceGuardFile = {
  path: string;
  content: string;
};

export function generateSourceGuardTest(
  input: SourceGuardGenerationInput,
): GeneratedSourceGuardFile {
  return {
    path: input.outputPath,
    content: `// AUTO-GENERATED by spec-to-pr.
// Guards API architecture boundaries.

import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const uiGlobs = ${JSON.stringify(input.uiGlobs, null, 2)};

const forbiddenPatterns = [
  {
    name: "direct fetch",
    pattern: /\\bfetch\\s*\\(/,
  },
  {
    name: "direct httpClient import",
    pattern: /from\\s+["'][^"']*http-client[^"']*["']/,
  },
  {
    name: "direct generated client import",
    pattern: new RegExp(${JSON.stringify(input.generatedImportPattern)}),
  },
];

describe("API source guards", () => {
  const files = uiGlobs.flatMap(resolveFiles);

  for (const file of files) {
    it(\`\${file} does not bypass API wrapper boundaries\`, () => {
      const content = readFileSync(file, "utf8");

      for (const forbidden of forbiddenPatterns) {
        expect(content, \`\${file} contains forbidden \${forbidden.name}\`).not.toMatch(
          forbidden.pattern,
        );
      }
    });
  }
});

function resolveFiles(pattern: string): string[] {
  const root = pattern.split("**")[0]?.replace(/\\/$/, "") ?? pattern;
  const extensions = new Set(
    [...pattern.matchAll(/\\{([^}]+)\\}/g)].flatMap((match) =>
      match[1]!.split(",").map((extension) => \`.\${extension.replace(/^\\./, "")}\`),
    ),
  );
  const fallbackExtensions = new Set([".ts", ".tsx"]);

  return walkFiles(root, extensions.size === 0 ? fallbackExtensions : extensions);
}

function walkFiles(root: string, extensions: Set<string>): string[] {
  if (!existsSync(root)) {
    return [];
  }

  const current = statSync(root);

  if (current.isFile()) {
    return extensions.has(path.extname(root)) ? [root] : [];
  }

  return readdirSync(root).flatMap((entry) => walkFiles(path.join(root, entry), extensions));
}
`,
  };
}
