import type { ObservabilityPlan } from "./telemetry-plan.js";
import { toOpenTelemetryResourceAttributes } from "./telemetry-resource.js";

export type RenderedObservabilityConfig = {
  otelNodeTs: string;
  loggerCorrelationTs: string;
  apiWrapperSpanTemplateTs: string;
  observabilityReadmeMd: string;
};

export function renderObservabilityConfig(plan: ObservabilityPlan): RenderedObservabilityConfig {
  return {
    otelNodeTs: renderOtelNodeConfig(plan),
    loggerCorrelationTs: renderLoggerCorrelation(),
    apiWrapperSpanTemplateTs: renderApiWrapperSpanTemplate(),
    observabilityReadmeMd: renderReadme(plan),
  };
}

function renderOtelNodeConfig(plan: ObservabilityPlan): string {
  const resourceAttributes = toOpenTelemetryResourceAttributes({
    serviceName: plan.serviceName,
    serviceVersion: plan.serviceVersion,
    serviceNamespace: "spec-to-pr-target",
    deploymentEnvironment: plan.environment,
  });

  return `import { NodeSDK } from "@opentelemetry/sdk-node";
import { ConsoleSpanExporter } from "@opentelemetry/sdk-trace-node";
import { ConsoleMetricExporter, PeriodicExportingMetricReader } from "@opentelemetry/sdk-metrics";
import { resourceFromAttributes } from "@opentelemetry/resources";

const resource = resourceFromAttributes(${JSON.stringify(resourceAttributes, null, 2)});

export const otelSdk = new NodeSDK({
  resource,
  traceExporter: new ConsoleSpanExporter(),
  metricReader: new PeriodicExportingMetricReader({
    exporter: new ConsoleMetricExporter(),
  }),
});

export async function startOpenTelemetry() {
  await otelSdk.start();
}

export async function shutdownOpenTelemetry() {
  await otelSdk.shutdown();
}
`;
}

function renderLoggerCorrelation(): string {
  return `import { trace } from "@opentelemetry/api";

export function currentTraceLogFields() {
  const spanContext = trace.getActiveSpan()?.spanContext();

  if (spanContext === undefined) {
    return {};
  }

  return {
    trace_id: spanContext.traceId,
    span_id: spanContext.spanId,
  };
}

export function withSpecToPrCorrelation(fields: Record<string, unknown>) {
  return {
    ...currentTraceLogFields(),
    ...fields,
  };
}
`;
}

function renderApiWrapperSpanTemplate(): string {
  return `import { SpanStatusCode, trace } from "@opentelemetry/api";

const tracer = trace.getTracer("api-wrapper");

export async function withApiWrapperSpan<T>(
  name: string,
  attributes: Record<string, string | number | boolean>,
  operation: () => Promise<T>,
): Promise<T> {
  return tracer.startActiveSpan(name, { attributes }, async (span) => {
    try {
      const result = await operation();
      span.setStatus({ code: SpanStatusCode.OK });
      return result;
    } catch (error) {
      span.recordException(error as Error);
      span.setStatus({
        code: SpanStatusCode.ERROR,
        message: error instanceof Error ? error.message : "Unknown error",
      });
      throw error;
    } finally {
      span.end();
    }
  });
}
`;
}

function renderReadme(plan: ObservabilityPlan): string {
  return `# Observability Setup

This folder was generated by spec-to-pr.

## Plan

- Target: ${plan.target}
- Exporter: ${plan.exporter}
- Traces: ${plan.enableTraces ? "enabled" : "disabled"}
- Metrics: ${plan.enableMetrics ? "enabled" : "disabled"}
- Log correlation: ${plan.enableLogCorrelation ? "enabled" : "disabled"}
- OTel logs: ${plan.enableOtelLogs ? "enabled" : "disabled"}
- API wrapper instrumentation: ${plan.apiWrapperInstrumentation ? "enabled" : "disabled"}

## Important

This setup is a template. Review your existing observability stack before applying it.

Do not export secrets as telemetry attributes.
`;
}
